### ISSUE TITLE
can support umd react component?

### ISSUE THREAD

**Issue by huguoliang1314** [Paciolan/remote-module-loader#12]
## Questions
  remote-module-loader is load a common.js module from a remote url, but i have a react component with umd module. use 
remote-module-loader has follow error:
![image](https://user-images.githubusercontent.com/13847571/114514109-8617b100-9c6d-11eb-9baf-8a2ed29fe3c5.png)

## usage
```javascript
import {
  createUseRemoteComponent,
  createRequires,
} from '@paciolan/remote-component';

import { resolve } from '../../../remote-component.config.js';

const requires = createRequires(resolve);
const fetcher = (url) =>
  fetch(url, { mode: 'cors', credentials: 'omit' }).then((res) => res.json());

export interface IProps {
  url: string;
  css?: string;
  name: string;
  children?: any;
}

const useRemoteComponent = createUseRemoteComponent({ requires, fetcher });

const LoadUmd = (props: IProps) => {
  const { url, name, css } = props || {};
  const [loading, err, Component] = useRemoteComponent(url);

  if (loading) {
    return <div>Loading...</div>;
  }

  if (err != null) {
    return <div>Unknown Error: {err.toString()}</div>;
  }

  return <Component {...props} />;
};

export default LoadUmd;
```

## i want

i want can load remote component with umd module  success

**Comment by dealenx** [comment]
Hi, 

I have a similar actual question.

I would be grateful if you could  found a solution  and briefly show how you figured it out.

**Comment by joelnet** [comment]
There are currently no plans to add support UMD. I would recommend creating a fork for a UMD version.
