### ISSUE TITLE
Remote module as Webpack chunked build

### ISSUE THREAD

**Issue by shanplourde** [Paciolan/remote-module-loader#15]
Hello, I have a Webpack 4 remote module built in commonjs form. The remote module built is also chunked. 

When consumed in my parent Webpack 4 application, the main entry chunk successfully loads, but once Webpack needs to request the remote module's chunks, it loads them from the domain of the consumer rather than the domain of the remote module.

I'm still researching whether or not this something that I can configure in Webpack, or if it's a bug. Appreciate any insights that you might have.

**Comment by joelnet** [comment]
This is going to be difficult for us to reproduce without a repository. Can you put something up on github so I can pull it and run it to easily replicate the issue you are having?

**Comment by shanplourde** [comment]
This was just a local development issue...it was resolved by setting up a local proxy in the consumer application.
