### ISSUE TITLE
Named Exports

### ISSUE THREAD

**Issue by seikosantana** [Paciolan/remote-module-loader#32]
Hi, is there a way to perform named imports using this library? I managed to fetch and I can see the result of `loadRemodeModule`, but I don't see any way to get what I exported beside `export default`.

I am exporting it like

```js
import { IotaboardDashboard } from "./IotaboardDashboard";
import _backgroundInit from "./background";

// Important: do not change name
export const backgroundInit = _backgroundInit;

export default IotaboardDashboard;
```

**Comment by joelnet** [comment]
Yes, named exports do work. I'll have to update the documentation, but it is supported.

In this example you can see the code is calling `.default()` you can change that to the name of your export. 

```javascript
/**
 * src/index.js
 */

import loadRemoteModule from "./lib/loadRemoteModule";

const main = async () => {
  const myModule = await loadRemoteModule(
    "http://fake.url/modules/my-module.js"
  );
  const value = myModule.default();
  console.log({ value });
};

main();
```

**Comment by seikosantana** [comment]
Ah yeah sorry forgot to close the issue. I previously tried the method just like you described above and it didn't work. After further investigating I realized that it was loading a disk-cached version.

Again, thanks a lot for the awesome library :grinning:
