### ISSUE TITLE
Mixed kind of exports, not supported by TypeScript

### ISSUE THREAD

**Issue by unlight** [Paciolan/remote-module-loader#4]
https://github.com/Paciolan/remote-module-loader/blob/master/src/index.js
```
export { createLoadRemoteModule as default } from "./lib/loadRemoteModule";
export { createRequires } from "./lib/createRequires";
```
One line import requires to write statement like this:
```ts
import createLoadRemoteModule, { createRequires  } from 'remote-module-loader';
```
Which is not supported by TypeScript

**Comment by joelnet** [comment]
We aren't using TypeScript, so it may take me a few days to play with this.

Is the problem using default as well as named exports?

Does it work when you do something like this?

```javascript
import createLoadRemoteModule from 'remote-module-loader';
import { createRequires  } from 'remote-module-loader';
```

**Comment by unlight** [comment]
Yes, 2 lines import will work.
The issue is about **one line** import.

**Comment by joelnet** [comment]
I just created a TypeScript file:

```typescript
import createLoadRemoteModule, { createRequires } from "@paciolan/remote-module-loader";

console.log({ createRequires, createLoadRemoteModule });
```

It appears to compile and run fine. the output is:

```
{ createRequires: [Function: createRequires],
  createLoadRemoteModule: [Function: createLoadRemoteModule] }
```

I tested this with TypeScript 3.5.3.

Can you confirm your version and maybe include a link to a github project for us to investigate further?

**Comment by unlight** [comment]
Apparently, fixed in some version after mine.
I'll update TypeScript, thanks.
